### PR TITLE
Update from original repo

### PR DESCRIPTION
**Pull request by dedepete**

### CODE REVIEW

**Comment by yakov116** [comment]
@dedepete whats you slack name?

**Comment by dedepete** [comment]
@yakov116 I'm not sure how to sign up there.

**Comment by yakov116** [comment]
@dedepete click on the slack svg on the main repo

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dedepete** [comment]
@yakov116 it says that invite link is not valid.

**Comment by yakov116** [comment]
@dedepete working on it

**Comment by yakov116** [comment]
http://rebrand.ly/fasthub

**Comment by dedepete** [comment]
image

**Comment by yakov116** [comment]
https://join.slack.com/fasthub/shared_invite/MTk2MDI1MDQyMzA4LTE0OTcxOTQyNDQtNGMxODM3Nzc2Zg

**Comment by dedepete** [comment]
Joined it, my username is `dedepete`

**Comment by yakov116** [comment]
Welcome aboard

**Pull request merged**
